// Contenido demostrativo. En una versión conectada a servidor, estos datos
// deberían leerse y guardarse mediante una API con acceso autenticado.
const initialProjects = [
  { id:'torre-natalini', name:'Torre Natalini', category:'Edificios', year:'2024', description:'Arquitectura moderna y de vanguardia en la ciudad de Resistencia. Una torre que transforma el perfil urbano.', image:'https://images.unsplash.com/photo-1487958449943-2429e8be8625?auto=format&fit=crop&w=1500&q=85', imageAlt:'Edificio contemporáneo de líneas claras', team:[{name:'María López',role:'Arquitectura',description:'Lideró el diseño arquitectónico y la relación del edificio con su entorno.',image:'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=500&q=80'},{name:'Estudio Norte',role:'Dirección / desarrollo',description:'Acompañó el desarrollo del proyecto desde la idea inicial hasta su planificación.',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=500&q=80'},{name:'Constructora Litoral',role:'Construcción',description:'Hizo posible la obra con un equipo comprometido con cada detalle.',image:'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=500&q=80'},{name:'Juan Pérez',role:'Diseño de interiores',description:'Trabajó en la materialidad y en los espacios comunes del edificio.',image:'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=500&q=80'}],news:[{date:'12/09/2026',type:'Avance de obra',title:'Estructura en etapa final',body:'La estructura principal alcanzó su último nivel. En las próximas semanas comienzan las tareas de cerramiento.'}]},
  { id:'uno-boulevard', name:'Uno Boulevard', category:'Edificios', year:'2023', description:'Volúmenes y líneas que generan diversidad de planos, luz natural y vistas abiertas.', image:'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1500&q=85', imageAlt:'Fachada residencial con balcones y vegetación', team:[{name:'Lucía Benítez',role:'Arquitectura',description:'Diseñó el juego de volúmenes y la apertura de los ambientes al paisaje.',image:'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=500&q=80'},{name:'Equipo MARQ',role:'Desarrollo',description:'Coordinó las distintas etapas del proyecto y su propuesta de valor.',image:'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=500&q=80'},{name:'Obras del Paraná',role:'Construcción',description:'Llevó adelante la obra y resolvió cada encuentro de materiales.',image:'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=500&q=80'}],news:[]},
  { id:'casa-bdn', name:'Casas BDN + Terreno', category:'Casas', year:'2024', description:'Tu casa y tu terreno en un barrio costero consolidado. Brisas del Norte es un proyecto habitado y en pleno crecimiento.', image:'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1500&q=85', imageAlt:'Interior de casa con materiales cálidos y luz natural', team:[{name:'Sofía Acosta',role:'Arquitectura',description:'Interpretó el terreno y organizó la casa para acercarla a las vistas.',image:'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=500&q=80'},{name:'Familia B.',role:'Comitentes',description:'Compartió su manera de vivir y sus deseos para orientar cada decisión.',image:'https://images.unsplash.com/photo-1511895426328-dc8714191300?auto=format&fit=crop&w=500&q=80'},{name:'Taller Madera',role:'Carpintería',description:'Realizó piezas a medida que suman calidez y carácter a la casa.',image:'https://images.unsplash.com/photo-1601058268499-e52658b8bb88?auto=format&fit=crop&w=500&q=80'}],news:[]},
  { id:'pueblo-mio', name:'Pueblo Mío', category:'Lotes', year:'2023', description:'Un barrio privado con laguna, espacios verdes y una nueva forma de conectar con el paisaje.', image:'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1500&q=85', imageAlt:'Paisaje verde con agua y vegetación', team:[{name:'Equipo Urbanismo MARQ',role:'Urbanismo',description:'Pensó la trama del barrio y la convivencia entre naturaleza y vida cotidiana.',image:'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=500&q=80'},{name:'Verde Vivo',role:'Paisajismo',description:'Definió especies y espacios para acompañar la identidad natural del lugar.',image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=500&q=80'},{name:'Desarrollo B.',role:'Desarrollo',description:'Impulsó el proyecto y articuló a los equipos que lo hicieron posible.',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=500&q=80'}],news:[]},
  { id:'casa-fo', name:'Casa FO', category:'Casas', year:'2022', description:'Un equilibrio entre calidad, confort y diseño para acompañar la vida de sus habitantes.', image:'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1500&q=85', imageAlt:'Casa contemporánea integrada con el exterior', team:[{name:'Tomás Fernández',role:'Arquitectura',description:'Desarrolló una propuesta funcional que aprovecha cada metro de la casa.',image:'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=500&q=80'},{name:'Estudio Luz',role:'Iluminación',description:'Acompañó el diseño con una propuesta de luz natural y artificial.',image:'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=500&q=80'}],news:[]},
  { id:'parque-arboledas', name:'Parque Arboledas', category:'Lotes', year:'2021', description:'Un loteo residencial que propone vivir cerca de la ciudad, rodeado de naturaleza.', image:'https://images.unsplash.com/photo-1470252649378-9c29740c9fa8?auto=format&fit=crop&w=1500&q=85', imageAlt:'Arboleda bañada por luz de tarde', team:[{name:'Carolina Ruiz',role:'Urbanismo',description:'Diseñó una propuesta que integra el trazado y el bosque nativo.',image:'https://images.unsplash.com/photo-1551836022-d5d88e9218df?auto=format&fit=crop&w=500&q=80'},{name:'Equipo de infraestructura',role:'Obras y servicios',description:'Planificó las redes y los espacios comunes que dan soporte al barrio.',image:'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=500&q=80'},{name:'Vivero Raíz',role:'Proveedores',description:'Aportó especies nativas y conocimiento local para el paisaje.',image:'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=500&q=80'}],news:[]}
];

const demoPeople = [
  {name:'Ana Martínez',project:'torre-natalini',interest:'Vivienda propia',status:'En conversación',phone:'5493624000001'},
  {name:'Diego Fernández',project:'torre-natalini',interest:'Inversión',status:'Información enviada',phone:'5493624000002'},
  {name:'Paula Gómez',project:'uno-boulevard',interest:'Vivienda propia',status:'Seguimiento pendiente',phone:'5493624000003'},
  {name:'Julián Benítez',project:'casa-bdn',interest:'Vivienda propia',status:'En conversación',phone:'5493624000004'},
  {name:'Carla Ruiz',project:'pueblo-mio',interest:'Inversión',status:'Interesado',phone:'5493624000005'},
  {name:'Marcos Vera',project:'parque-arboledas',interest:'Información pendiente',status:'Sin clasificar',phone:'5493624000006'}
];
const saved = (()=>{try{return JSON.parse(localStorage.getItem('marq-projects-v1'))}catch{return null}})();
const projects = Array.isArray(saved) ? saved : initialProjects;
const people = demoPeople;
const grid=document.querySelector('#projects-grid');
const modal=document.querySelector('#team-modal');
const teamGrid=document.querySelector('#team-grid');
const companyView=document.querySelector('#company-view');
const modeToggle=document.querySelector('#mode-toggle');
let previousFocus=null, companyMode=false, activeProject=null, peopleFilter='', newsFollowupId=null, selectedPeople=[], messageDraft=null;
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const saveProjects=()=>localStorage.setItem('marq-projects-v1',JSON.stringify(projects));

function renderProjects(filter='Todos'){
  const displayOrder=['casa-bdn','torre-natalini','uno-boulevard','pueblo-mio','casa-fo','parque-arboledas'];
  const visible=projects.filter(project=>filter==='Todos'||project.category===filter).sort((a,b)=>displayOrder.indexOf(a.id)-displayOrder.indexOf(b.id));
  grid.innerHTML=visible.map((project,index)=>`<article class="project-card" id="${esc(project.id)}">
    <div class="project-image-wrap"><img class="project-image" src="${esc(project.image)}" alt="${esc(project.imageAlt)}" loading="lazy"><span class="image-count">0${index+1} / 0${projects.length}</span></div>
    <div class="project-info"><div class="project-meta"><span class="project-category">${esc(project.category)}</span><span class="project-year">${esc(project.year)}</span></div>
    <h2 class="project-title">${esc(project.name)}</h2><p class="project-description">${esc(project.description)}</p>
    <div class="project-actions"><a class="project-link" href="mailto:hola@estudiomarq.com.ar?subject=${encodeURIComponent(`Consulta por ${project.name}`)}">Consultar por este proyecto <span>↗</span></a><button class="team-link" data-project="${esc(project.id)}">Conocé quiénes están detrás <span>↗</span></button></div></div></article>`).join('');
  grid.querySelectorAll('.team-link').forEach(button=>button.addEventListener('click',()=>openTeam(button.dataset.project)));
  grid.querySelectorAll('.project-card').forEach(card=>card.addEventListener('click',event=>{if(companyMode&&!event.target.closest('a,button'))openCompanyProject(card.id)}));
}
function openTeam(id){
  const project=projects.find(item=>item.id===id); if(!project)return;
  previousFocus=document.activeElement;
  modal.querySelector('#modal-title').textContent=project.name;
  modal.querySelector('.modal-category').textContent=project.category;
  modal.querySelector('.modal-index').textContent=`PROYECTO ${String(projects.indexOf(project)+1).padStart(2,'0')} / 0${projects.length}`;
  teamGrid.innerHTML=`${project.team.map(person=>`<article class="person-card"><img class="person-photo" src="${esc(person.image)}" alt="Retrato demostrativo de ${esc(person.name)}" loading="lazy"><div class="person-content"><span class="person-role">${esc(person.role)}</span><h4 class="person-name">${esc(person.name)}</h4><p class="person-description">${esc(person.description)}</p></div></article>`).join('')}
    <section class="public-updates"><span class="eyebrow"><span class="eyebrow-line"></span> NOVEDADES DEL PROYECTO</span><h3>Lo último de ${esc(project.name)}</h3>${project.news?.length?project.news.map(item=>`<article class="update-card"><span>${esc(item.date)} · ${esc(item.type)}</span><h4>${esc(item.title)}</h4><p>${esc(item.body)}</p></article>`).join(''):'<p class="updates-empty">Pronto compartiremos novedades de este proyecto.</p>'}</section>`;
  modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open');modal.querySelector('.modal-close').focus();
}
function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open');if(previousFocus)previousFocus.focus()}
function setMode(enabled){companyMode=enabled;document.body.classList.toggle('company-mode',enabled);companyView.hidden=true;document.querySelector('main').hidden=false;document.querySelector('footer').hidden=false;document.querySelector('.whatsapp').hidden=enabled;modeToggle.textContent=enabled?'Volver a vista cliente ↗':'Acceso empresa ↗';activeProject=null;newsFollowupId=null;messageDraft=null;renderProjects(document.querySelector('.filter.active')?.dataset.filter||'Todos')}
function openCompanyProject(id){activeProject=id;peopleFilter='';newsFollowupId=null;selectedPeople=[];messageDraft=null;document.querySelector('main').hidden=true;document.querySelector('footer').hidden=true;companyView.hidden=false;renderCompany()}
function renderCompany(){
  const project=projects.find(item=>item.id===activeProject)||projects[0];activeProject=project.id;
  const related=people.filter(person=>person.project===project.id).filter(person=>!peopleFilter||`${person.name} ${person.interest} ${person.status}`.toLowerCase().includes(peopleFilter.toLowerCase()));
  const fresh=project.news?.find(item=>item.id===newsFollowupId);
  const peoplePanel=`<section class="admin-panel people-panel"><div class="admin-panel-head"><div><h2>${fresh?'Personas asociadas a esta novedad':'Personas asociadas'}</h2><p>${fresh?`${esc(fresh.title)} · ${fresh.contactIds.length} personas vinculadas al proyecto`:'Filtrá los contactos vinculados con este proyecto.'}</p></div>${fresh?`<span class="demo-label">${selectedPeople.length} seleccionadas</span>`:''}</div><label class="people-search"><span>⌕</span><input id="people-search" value="${esc(peopleFilter)}" placeholder="Filtrar por nombre, interés o estado"></label><div class="associated-list">${related.length?related.map(person=>fresh?`<label class="associated-person associated-select"><input type="checkbox" data-person="${esc(person.name)}" ${selectedPeople.includes(person.name)?'checked':''}><span class="company-avatar">${esc(person.name.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase())}</span><span class="associated-copy"><b>${esc(person.name)}</b><small>${esc(person.interest)} · ${esc(person.status)}</small></span></label>`:`<article class="associated-person"><span class="company-avatar">${esc(person.name.split(' ').map(part=>part[0]).slice(0,2).join('').toUpperCase())}</span><span class="associated-copy"><b>${esc(person.name)}</b><small>${esc(person.interest)}</small></span><span class="status-chip">${esc(person.status)}</span></article>`).join(''):'<p class="admin-empty">No hay personas que coincidan con el filtro.</p>'}</div>${fresh?`<div class="people-actions"><button class="admin-secondary" id="select-all-people">Seleccionar todos</button><button class="admin-primary" id="prepare-contact" ${selectedPeople.length?'':'disabled'}>Preparar contacto →</button></div>${messageDraft?`<div class="message-composer"><div class="admin-panel-head"><div><h3>Mensaje sugerido</h3><p>Para ${esc(messageDraft.name)} · revisalo antes de abrir WhatsApp.</p></div></div><textarea id="message-text">${esc(messageDraft.message)}</textarea><a class="admin-primary whatsapp-link" id="open-whatsapp" href="${esc(whatsappUrl(messageDraft))}" target="_blank" rel="noopener">Abrir WhatsApp con mensaje ↗</a></div>`:''}`:'<p class="privacy-note">La información de contactos solo aparece en este espacio de empresa.</p>'}</section>`;
  companyView.innerHTML=`<div class="company-detail"><div class="company-content"><div class="company-detail-top"><button class="admin-back" id="back-to-projects">← Volver a proyectos</button><span class="demo-label">VISTA EMPRESA · PROTOTIPO</span></div><div class="company-heading"><div><span class="eyebrow">${esc(project.category)} · ${esc(project.year)}</span><h1>${esc(project.name)}</h1><p>${esc(project.description)}</p></div><button class="admin-primary" id="add-update">＋ Agregar novedad</button></div><div class="company-stats"><article><span>Personas asociadas</span><b>${people.filter(person=>person.project===project.id).length}</b></article><article><span>Novedades registradas</span><b>${project.news?.length||0}</b></article><article><span>Última actualización</span><b>${project.news?.[0]?.date||'Sin novedades'}</b></article></div><div class="company-columns">${peoplePanel}<section class="admin-panel updates-panel"><div class="admin-panel-head"><div><h2>Novedades</h2><p>Actualizaciones del proyecto visibles para clientes.</p></div></div>${project.news?.length?project.news.map(item=>`<article class="admin-update"><div><span>${esc(item.date)} · ${esc(item.type)}</span><h3>${esc(item.title)}</h3><p>${esc(item.body)}</p></div></article>`).join(''):'<div class="admin-empty">Todavía no hay novedades. Agregá la primera actualización del proyecto.</div>'}</section></div></div></div>`;
  companyView.querySelector('#back-to-projects').addEventListener('click',()=>{companyView.hidden=true;document.querySelector('main').hidden=false;document.querySelector('footer').hidden=false;activeProject=null});
  companyView.querySelector('#people-search').addEventListener('input',event=>{peopleFilter=event.target.value;const pos=event.target.selectionStart;renderCompany();const input=companyView.querySelector('#people-search');input.focus();input.setSelectionRange(pos,pos)});
  companyView.querySelectorAll('[data-person]').forEach(input=>input.addEventListener('change',()=>{selectedPeople=input.checked?[...selectedPeople,input.dataset.person]:selectedPeople.filter(name=>name!==input.dataset.person);messageDraft=null;renderCompany()}));
  companyView.querySelector('#select-all-people')?.addEventListener('click',()=>{selectedPeople=related.map(person=>person.name);messageDraft=null;renderCompany()});
  companyView.querySelector('#prepare-contact')?.addEventListener('click',()=>{const person=people.find(item=>item.name===selectedPeople[0]&&item.project===project.id);if(!person)return;messageDraft={name:person.name,phone:person.phone,message:`Hola ${person.name.split(' ')[0]}, ¿cómo estás? Te escribo porque hace unos días habías consultado por ${project.name} y tenemos una novedad que quizás pueda interesarte: ${fresh.title.toLowerCase()}. Si querés, puedo contarte un poco más sobre esta opción.`};renderCompany()});
  companyView.querySelector('#message-text')?.addEventListener('input',event=>{messageDraft.message=event.target.value;companyView.querySelector('#open-whatsapp').href=whatsappUrl(messageDraft)});
  companyView.querySelector('#add-update').addEventListener('click',openUpdateForm);
}
function whatsappUrl(draft){return `https://wa.me/${draft.phone}?text=${encodeURIComponent(draft.message)}`}
function openUpdateForm(){const project=projects.find(item=>item.id===activeProject);const backdrop=document.createElement('div');backdrop.className='update-dialog-backdrop';backdrop.innerHTML=`<form class="update-dialog"><div class="admin-panel-head"><div><span class="eyebrow">${esc(project.name)}</span><h2>Nueva novedad</h2></div><button type="button" class="dialog-close" aria-label="Cerrar">×</button></div><p>Esta actualización quedará visible para las personas que visiten el proyecto.</p><label>Tipo de novedad<select name="type"><option>Avance de obra</option><option>Disponibilidad</option><option>Evento</option><option>Información relevante</option></select></label><label>Título<input name="title" required maxlength="100" placeholder="Ej. Nueva etapa de obra"></label><label>Detalle<textarea name="body" required maxlength="500" placeholder="Contá brevemente qué cambió."></textarea></label><div class="dialog-actions"><button type="button" class="admin-secondary">Cancelar</button><button class="admin-primary" type="submit">Publicar novedad</button></div></form>`;
  const dismiss=()=>backdrop.remove();backdrop.addEventListener('click',event=>{if(event.target===backdrop)dismiss()});backdrop.querySelectorAll('.dialog-close,.admin-secondary').forEach(button=>button.addEventListener('click',dismiss));backdrop.querySelector('form').addEventListener('submit',event=>{event.preventDefault();const form=new FormData(event.currentTarget),contactIds=people.filter(person=>person.project===project.id).map(person=>person.name);project.news=project.news||[];const item={id:Date.now(),date:new Intl.DateTimeFormat('es-AR').format(new Date()),type:form.get('type'),title:String(form.get('title')).trim(),body:String(form.get('body')).trim(),contactIds};project.news.unshift(item);newsFollowupId=item.id;peopleFilter='';selectedPeople=[];messageDraft=null;saveProjects();dismiss();renderCompany()});document.body.append(backdrop);backdrop.querySelector('input').focus();
}
document.querySelectorAll('.filter').forEach(button=>button.addEventListener('click',()=>{document.querySelector('.filter.active')?.classList.remove('active');button.classList.add('active');renderProjects(button.dataset.filter)}));
modal.querySelectorAll('[data-close-modal]').forEach(button=>button.addEventListener('click',closeModal));
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&modal.classList.contains('open'))closeModal();if(event.key==='Escape')document.querySelector('.update-dialog-backdrop')?.remove()});
modeToggle.addEventListener('click',()=>setMode(!companyMode));
const menuButton=document.querySelector('.menu-toggle');
menuButton.addEventListener('click',()=>{const nav=document.querySelector('.main-nav');const isOpen=nav.classList.toggle('mobile-open');menuButton.setAttribute('aria-expanded',String(isOpen));menuButton.setAttribute('aria-label',isOpen?'Cerrar navegación':'Abrir navegación')});
document.querySelectorAll('.main-nav a').forEach(link=>link.addEventListener('click',()=>{document.querySelector('.main-nav').classList.remove('mobile-open');menuButton.setAttribute('aria-expanded','false')}));
renderProjects();
